after-login-command = []
after-startup-command = []

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'
alt-shift-m = 'fullscreen'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-enter = 'exec-and-forget open -n /Applications/Ghostty.app'
alt-s = 'exec-and-forget open -n /Applications/Slack.app'
alt-w = 'exec-and-forget open -n /Applications/WhatsApp.app'
alt-b = 'exec-and-forget open -n /Applications/Firefox.app'
alt-d = 'exec-and-forget open -n /Applications/MySQLWorkbench.app'
alt-m = 'exec-and-forget open -n /Applications/Spotify.app'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'

alt-n = 'workspace N'
alt-y = 'workspace Y'
alt-u = 'workspace U'
alt-i = 'workspace I'
alt-o = 'workspace O'
alt-p = 'workspace P'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'

alt-shift-n = 'move-node-to-workspace N'
alt-shift-y = 'move-node-to-workspace Y'
alt-shift-u = 'move-node-to-workspace U'
alt-shift-i = 'move-node-to-workspace I'
alt-shift-o = 'move-node-to-workspace O'
alt-shift-p = 'move-node-to-workspace P'

alt-tab = 'workspace-back-and-forth'
alt-shift-f = 'layout floating tiling'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
