#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar position=top \
  height=30 \
  blur_radius=30 \
  color=$BAR_COLOR \

##### Changing Defaults #####
default=(
  padding_left=6
  padding_right=6
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=6
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=6
  background.corner_radius=5
  background.height=24
  background.color=$ITEM_BG_COLOR
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
source $ITEM_DIR/aerospace.sh

##### Adding Right Items #####
source $ITEM_DIR/clock.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
