#!/usr/bin/env bash

session="prod"
skip_attach=0
workspace="$HOME/Work/Development/workspace-prod"
web_project="$workspace/web-eloverde"
api_project="$workspace/api-eloverde"

if [ "${1:-}" = "--no-attach" ] || [ "${1:-}" = "-n" ]; then
    skip_attach=1
fi

tmux has-session -t "$session" 2>/dev/null

if [ $? != 0 ]; then
    
    # create session
    tmux new-session -s "$session" -n "workspace" -c "$workspace" -d

    # setup web project window
    tmux new-window -t "$session" -n "web-eloverde" -c "$web_project"
    tmux send-keys -t "$session":web-eloverde "cl" C-m
    tmux send-keys -t "$session":web-eloverde "vim" C-m
    tmux split-window -v -p 33 -t "$session":web-eloverde -c "$web_project"
    tmux send-keys -t "$session":web-eloverde.2 "cl" C-m

    # setup api project window
    tmux new-window -t "$session" -n "api-eloverde" -c "$api_project"
    tmux send-keys -t "$session":api-eloverde "cl" C-m
    tmux send-keys -t "$session":api-eloverde "vim" C-m
    tmux split-window -v -p 33 -t "$session":api-eloverde -c "$api_project"
    tmux send-keys -t "$session":api-eloverde.2 "cl" C-m
    tmux split-window -h -t "$session":api-eloverde.2 -c "$api_project"
    tmux send-keys -t "$session":api-eloverde.3 "cl" C-m

    # select workspace window
    tmux select-window -t "$session":workspace
fi

if [ "$skip_attach" -eq 0 ]; then
    if [ -n "$TMUX" ]; then
        tmux switch-client -t $session
    else
        tmux attach -t $session
    fi
fi

exit 0
