#!/usr/bin/env bash

# Based on the tmux-sessionizer script by ThePrimeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~ ~/Work/Development/dev ~/Work/Development ~/Development \
        -mindepth 1 -maxdepth 2 -type d \
        -path "$HOME/.Trash" -prune -o -print | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected-1" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 1
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [ -n "$TMUX" ]; then
    tmux switch-client -t $selected_name
else
    tmux attach -t $selected_name
fi
