#!/usr/bin/env bash

# Based on the tmux-windownizer script by ThePrimeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~ ~/Work/Development/dev ~/Work/Development ~/Development \
        -mindepth 1 -maxdepth 2 -type d \
        -path "$HOME/.Trash" -prune -o -print | fzf --bind 'ctrl-y:accept')
fi


if [[ -z $selected ]]; then
    echo "No dir selected."
    exit 0
fi

if [[ ! -d "$selected" ]]; then
    echo "Erro: directory not found!"
    exit 1
fi

branch_name=$(basename "$selected" | tr . _)
clean_name=$(echo "$branch_name" | tr "./" "__")

if [ -z "$TMUX" ]; then
    echo "You must be inside a tmux session to run this script."
    exit 1
fi

# Adiciona uma nova janela à sessão atual
tmux new-window -n "$clean_name" -c "$selected"
