#!/usr/bin/env bash

session="prod"

tmux has-session -t $session 2> /dev/null

if [ $? != 0 ]; then
    # if session exists attach to it
    if tmux has-session -t "$session" 2>/dev/null; then
        tmux attach-session -t "$session"

        exit 0
    fi
    
    # create session
    tmux new-session -s $session -n "web-eloverde" -c "$HOME/Work/Development/prod" -d

    # setup editor window
    tmux send-keys -t $session:web-eloverde "cd $HOME/Work/Development/prod/web-eloverde" C-m
    tmux send-keys -t $session:web-eloverde "cl" C-m
    tmux send-keys -t $session:web-eloverde "vim" C-m

    # setup build pane
    tmux split-window -v -t $session:web-eloverde -c "$HOME/Work/Development/prod/web-eloverde"
    tmux resize-pane -D 10
    tmux send-keys -t $session:web-eloverde.2 "cl" C-m
    tmux send-keys -t $session:web-eloverde.2 "npm run serve" C-m

    # setup api window
    tmux new-window  -t $session -n "api-eloverde" -c "$HOME/Work/Development/prod/api-eloverde"
    tmux send-keys -t $session:api-eloverde "cl" C-m
    tmux send-keys -t $session:api-eloverde "vim" C-m

    # setup api serve pane
    tmux split-window -v -t $session:api-eloverde -c "$HOME/Work/Development/prod/api-eloverde"
    tmux resize-pane -D 10
    tmux send-keys -t $session:api-eloverde.2 "cl" C-m
    tmux send-keys -t $session:api-eloverde.2 "p-serve" C-m

    tmux split-window -h -t $session:api-eloverde.2 -c "$HOME/Work/Development/prod/api-eloverde"
    tmux resize-pane -L 50

    # select web editor
    tmux select-window -t $session:web-eloverde.1
fi

if [ -n "$TMUX" ]; then
    tmux switch-client -t $session
else
    tmux attach -t $session
fi

exit 0
