#!/usr/bin/env bash

# Based on the tmux-sessionizer script by ThePrimeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~ ~/Work/Development/dev ~/Work/Development ~/Development \
        -mindepth 1 -maxdepth 2 -type d \
        -path "$HOME/.Trash" -prune -o -print | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

base_name=$(basename "$selected" | tr . _ | tr -c '[:alnum:]' '_')
base_name="${base_name%%_}"
session_name=$base_name
index=1

while tmux has-session -t="$session_name" 2>/dev/null; do
    session_name="${base_name}_${index}"
    ((index++))
done

tmux new-session -ds "$session_name" -c "$selected"

if [ -n "$TMUX" ]; then
    tmux switch-client -t "$session_name"
else
    tmux attach -t "$session_name"
fi
